### ISSUE TITLE
Новые обновления

### ISSUE THREAD

**Issue by lex111** [sebastianbergmann/phpunit-documentation-russian#11]
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/cedc470c0cdc529037ab8b4794aafbc564c2ba54
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/1e5a58388a67508214360265cd9740c2b62d90ef
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/2d78db9e7a508b068e8640d6ad44a27b9c3787c6

**Comment by sebastianbergmann** [comment]
The PHPUnit project does not have the resources to coordinate the translation of the PHPUnit documentation into other languages. Some, if not most, of the existing translations have not been up-to-date with the English documentation for quite a while. I have therefore decided to no longer officially support documentation languages other than English. I apologize for any inconvenience this may cause.

I would like to use this opportunity to thank everybody who contributed to this translation effort over the years. Please feel free to continue your translation effort in a fork of this repository.

This repository is about to be archived and the translation of PHPUnit's documentation that was developed in this repository should no longer be considered official.
