### ISSUE TITLE
Обновить writing-tests-for-phpunit

### ISSUE THREAD

**Issue by lex111** [sebastianbergmann/phpunit-documentation-russian#8]
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/5b2262b9808321cf2e0f54ba476eb871e4af2cb2

**Comment by sebastianbergmann** [comment]
The PHPUnit project does not have the resources to coordinate the translation of the PHPUnit documentation into other languages. Some, if not most, of the existing translations have not been up-to-date with the English documentation for quite a while. I have therefore decided to no longer officially support documentation languages other than English. I apologize for any inconvenience this may cause.

I would like to use this opportunity to thank everybody who contributed to this translation effort over the years. Please feel free to continue your translation effort in a fork of this repository.

This repository is about to be archived and the translation of PHPUnit's documentation that was developed in this repository should no longer be considered official.
